googletest: Import from meta-openembedded
From meta-openembedded at commit 98f9507a73f015f24a9a01e716654524e848f9
("googletest: fix build with gcc-15").

This is needed by sdbus-c++ recipe (which is a build dependency
of dnf5) so import it in oe-core.

Avoids following error when bitbaking sdbus-c++ for target:

  ERROR: Nothing PROVIDES 'gmock' (but /build/nm/upstream/meta/recipes-core/sdbus-c++/sdbus-c++_2.1.0.bb DEPENDS on or otherwise requires it)

While importing, we drop the now-redundant S override from the recipe.

Signed-off-by: Niko Mauno <niko.mauno@vaisala.com>